package com.example.cocktailtaskapp.dashboard.model


import com.google.gson.annotations.SerializedName

data class DrinkModel(
    val dateModified: String = "",
    val idDrink: String = "",
    val strAlcoholic: String = "",
    val strCategory: String = "",
    val strCreativeCommonsConfirmed: String = "",
    val strDrink: String = "",
    val strDrinkAlternate: Any? = null,
    val strDrinkThumb: String = "",
    val strGlass: String = "",
    val strIBA: Any?= null,
    val strImageAttribution: Any? = null,
    val strImageSource: Any? = null,
    val strIngredient1: String = "",
    val strIngredient10: Any? = null,
    val strIngredient11: Any? = null,
    val strIngredient12: Any? = null,
    val strIngredient13: Any? = null,
    val strIngredient14: Any? = null,
    val strIngredient15: Any? = null,
    val strIngredient2: String = "",
    val strIngredient3: String = "",
    val strIngredient4: Any? = null,
    val strIngredient5: Any? = null,
    val strIngredient6: Any? = null,
    val strIngredient7: Any? = null,
    val strIngredient8: Any? = null,
    val strIngredient9: Any? = null,
    val strInstructions: String = "",
    val strInstructionsDE: String = "",
    val strInstructionsES: String = "",
    val strInstructionsFR: String = "",
    val strInstructionsIT: String = "",
    @SerializedName("strInstructionsZH-HANS")
    val strInstructionsZHHANS: Any? = null,
    @SerializedName("strInstructionsZH-HANT")
    val strInstructionsZHHANT: Any? = null,
    val strMeasure1: String = "",
    val strMeasure10: Any? = null,
    val strMeasure11: Any? = null,
    val strMeasure12: Any? = null,
    val strMeasure13: Any?= null,
    val strMeasure14: Any? = null,
    val strMeasure15: Any? = null,
    val strMeasure2: String = "",
    val strMeasure3: String = "",
    val strMeasure4: Any? = null,
    val strMeasure5: Any?= null,
    val strMeasure6: Any? = null,
    val strMeasure7: Any? = null,
    val strMeasure8: Any? = null,
    val strMeasure9: Any? = null,
    val strTags: String = "",
    val strVideo: Any? = null
)